 // Configuration for specialty-specific trail settings
 
 export interface SpecialtyConfig {
   id: string;
   label: string;
   category: "medicine" | "nutrition" | "psychology" | "physiotherapy" | "dentistry" | "other";
   clinicalConditionLabel: string;
   clinicalConditionPlaceholder: string;
   clinicalObjectiveLabel: string;
   clinicalObjectivePlaceholder: string;
   suggestedDurations: { value: number; label: string }[];
   structuredDataTypes: { value: string; label: string }[];
   suggestedContactPoints: { type: string; label: string; description: string }[];
   criticalKeywords: string[];
   defaultIcon: string;
 }
 
 // Structured data types by specialty
 export const STRUCTURED_DATA_BY_SPECIALTY = {
   medicine: [
     { value: "glucose", label: "Glicemia (mg/dL)" },
     { value: "blood_pressure", label: "Pressão Arterial (mmHg)" },
     { value: "weight", label: "Peso (kg)" },
     { value: "temperature", label: "Temperatura (°C)" },
     { value: "heart_rate", label: "Frequência Cardíaca (bpm)" },
     { value: "oxygen_saturation", label: "Saturação O2 (%)" },
     { value: "pain_scale", label: "Escala de Dor (0-10)" },
     { value: "adherence", label: "Adesão ao Tratamento (%)" },
     { value: "custom_numeric", label: "Valor Numérico Personalizado" },
     { value: "custom_text", label: "Texto Personalizado" },
   ],
   nutrition: [
     { value: "weight", label: "Peso (kg)" },
     { value: "body_fat", label: "% Gordura Corporal" },
     { value: "waist_circumference", label: "Circunferência Abdominal (cm)" },
     { value: "water_intake", label: "Ingestão de Água (L)" },
     { value: "meal_adherence", label: "Adesão ao Plano Alimentar (%)" },
     { value: "hunger_scale", label: "Escala de Fome (1-10)" },
     { value: "satiety_scale", label: "Escala de Saciedade (1-10)" },
     { value: "food_diary", label: "Registro Alimentar" },
     { value: "custom_numeric", label: "Valor Numérico Personalizado" },
     { value: "custom_text", label: "Texto Personalizado" },
   ],
   psychology: [
     { value: "mood", label: "Humor (1-10)" },
     { value: "anxiety_level", label: "Nível de Ansiedade (0-10)" },
     { value: "sleep_quality", label: "Qualidade do Sono (1-10)" },
     { value: "sleep_hours", label: "Horas de Sono" },
     { value: "stress_level", label: "Nível de Estresse (0-10)" },
     { value: "energy_level", label: "Nível de Energia (1-10)" },
     { value: "social_interaction", label: "Interação Social (1-10)" },
     { value: "thought_diary", label: "Registro de Pensamentos" },
     { value: "custom_numeric", label: "Valor Numérico Personalizado" },
     { value: "custom_text", label: "Texto Personalizado" },
   ],
   physiotherapy: [
     { value: "pain_scale", label: "Escala de Dor (0-10)" },
     { value: "range_of_motion", label: "Amplitude de Movimento (graus)" },
     { value: "exercise_adherence", label: "Adesão aos Exercícios (%)" },
     { value: "functional_score", label: "Score Funcional (0-100)" },
     { value: "walking_distance", label: "Distância Caminhada (metros)" },
     { value: "exercise_duration", label: "Duração do Exercício (min)" },
     { value: "repetitions", label: "Número de Repetições" },
     { value: "mobility_score", label: "Score de Mobilidade (1-10)" },
     { value: "custom_numeric", label: "Valor Numérico Personalizado" },
     { value: "custom_text", label: "Texto Personalizado" },
   ],
   dentistry: [
     { value: "pain_scale", label: "Escala de Dor (0-10)" },
     { value: "brushing_frequency", label: "Frequência de Escovação (vezes/dia)" },
     { value: "flossing_frequency", label: "Uso do Fio Dental (vezes/dia)" },
     { value: "sensitivity_level", label: "Nível de Sensibilidade (0-10)" },
     { value: "bleeding_gums", label: "Sangramento Gengival (0-3)" },
     { value: "mouthwash_use", label: "Uso de Enxaguante (vezes/dia)" },
     { value: "oral_hygiene_score", label: "Score Higiene Bucal (1-10)" },
     { value: "custom_numeric", label: "Valor Numérico Personalizado" },
     { value: "custom_text", label: "Texto Personalizado" },
   ],
   other: [
     { value: "pain_scale", label: "Escala de Dor (0-10)" },
     { value: "adherence", label: "Adesão ao Plano (%)" },
     { value: "mood", label: "Humor (1-10)" },
     { value: "custom_numeric", label: "Valor Numérico Personalizado" },
     { value: "custom_text", label: "Texto Personalizado" },
   ],
 };
 
 export const SPECIALTY_CONFIGS: Record<string, SpecialtyConfig> = {
   // Medicine specialties
   "Cardiologia": {
     id: "cardiologia",
     label: "Cardiologia",
     category: "medicine",
     clinicalConditionLabel: "Condição Cardiovascular",
     clinicalConditionPlaceholder: "Ex: Hipertensão Arterial, ICC, Arritmia",
     clinicalObjectiveLabel: "Objetivo Clínico",
     clinicalObjectivePlaceholder: "Ex: Controle pressórico < 140/90 mmHg",
     suggestedDurations: [
       { value: 30, label: "30 dias - Acompanhamento inicial" },
       { value: 60, label: "60 dias - Ajuste terapêutico" },
       { value: 90, label: "90 dias - Estabilização" },
     ],
     structuredDataTypes: STRUCTURED_DATA_BY_SPECIALTY.medicine,
     suggestedContactPoints: [
       { type: "structured_data", label: "Aferição de PA", description: "Registro diário de pressão" },
       { type: "educational_message", label: "Orientação sobre sal", description: "Dicas de redução de sódio" },
       { type: "reminder", label: "Lembrete de medicação", description: "Horário do anti-hipertensivo" },
     ],
     criticalKeywords: ["dor no peito", "falta de ar", "palpitação", "desmaio", "tontura intensa", "inchaço"],
     defaultIcon: "heart",
   },
   "Endocrinologia": {
     id: "endocrinologia",
     label: "Endocrinologia",
     category: "medicine",
     clinicalConditionLabel: "Condição Endócrina",
     clinicalConditionPlaceholder: "Ex: Diabetes Mellitus Tipo 2, Hipotireoidismo",
     clinicalObjectiveLabel: "Meta Terapêutica",
     clinicalObjectivePlaceholder: "Ex: HbA1c < 7%, TSH normalizado",
     suggestedDurations: [
       { value: 30, label: "30 dias - Monitoramento inicial" },
       { value: 60, label: "60 dias - Ajuste de dose" },
       { value: 90, label: "90 dias - Reavaliação" },
     ],
     structuredDataTypes: STRUCTURED_DATA_BY_SPECIALTY.medicine,
     suggestedContactPoints: [
       { type: "structured_data", label: "Glicemia capilar", description: "Registro de glicemia em jejum" },
       { type: "structured_data", label: "Registro de peso", description: "Acompanhamento ponderal" },
       { type: "reminder", label: "Lembrete de insulina", description: "Aplicação nos horários" },
     ],
     criticalKeywords: ["hipoglicemia", "tontura", "sudorese", "confusão", "glicemia alta", "sede excessiva"],
     defaultIcon: "activity",
   },
   "Clínica Médica": {
     id: "clinica-medica",
     label: "Clínica Médica",
     category: "medicine",
     clinicalConditionLabel: "Condição Clínica Principal",
     clinicalConditionPlaceholder: "Ex: HAS + DM2, Síndrome Metabólica",
     clinicalObjectiveLabel: "Objetivo do Acompanhamento",
     clinicalObjectivePlaceholder: "Ex: Controle de fatores de risco cardiovascular",
     suggestedDurations: [
       { value: 30, label: "30 dias - Check-up" },
       { value: 60, label: "60 dias - Seguimento" },
       { value: 90, label: "90 dias - Reavaliação completa" },
     ],
     structuredDataTypes: STRUCTURED_DATA_BY_SPECIALTY.medicine,
     suggestedContactPoints: [
       { type: "open_question", label: "Sintomas gerais", description: "Como está se sentindo?" },
       { type: "reminder", label: "Medicações", description: "Lembrete geral" },
     ],
     criticalKeywords: ["febre alta", "dor intensa", "sangramento", "desmaio", "confusão mental"],
     defaultIcon: "stethoscope",
   },
   // Nutrition
   "Nutrição": {
     id: "nutricao",
     label: "Nutrição",
     category: "nutrition",
     clinicalConditionLabel: "Objetivo Nutricional",
     clinicalConditionPlaceholder: "Ex: Emagrecimento, Ganho de massa, Reeducação alimentar",
     clinicalObjectiveLabel: "Meta Nutricional",
     clinicalObjectivePlaceholder: "Ex: Perda de 5kg em 3 meses, Redução de % gordura",
     suggestedDurations: [
       { value: 15, label: "15 dias - Adaptação inicial" },
       { value: 30, label: "30 dias - Fase 1" },
       { value: 60, label: "60 dias - Consolidação" },
       { value: 90, label: "90 dias - Programa completo" },
     ],
     structuredDataTypes: STRUCTURED_DATA_BY_SPECIALTY.nutrition,
     suggestedContactPoints: [
       { type: "structured_data", label: "Peso semanal", description: "Registro de peso" },
       { type: "structured_data", label: "Diário alimentar", description: "Registro de refeições" },
       { type: "closed_question", label: "Adesão ao plano", description: "Seguiu o cardápio?" },
       { type: "open_question", label: "Dificuldades", description: "Quais foram os desafios?" },
       { type: "educational_message", label: "Dica nutricional", description: "Orientações educativas" },
     ],
     criticalKeywords: ["compulsão", "vômito", "não consigo comer", "dor abdominal", "descontrole"],
     defaultIcon: "apple",
   },
   // Psychology
   "Psicologia": {
     id: "psicologia",
     label: "Psicologia",
     category: "psychology",
     clinicalConditionLabel: "Foco Terapêutico",
     clinicalConditionPlaceholder: "Ex: Ansiedade, Depressão, Relacionamentos",
     clinicalObjectiveLabel: "Objetivo Terapêutico",
     clinicalObjectivePlaceholder: "Ex: Redução de sintomas ansiosos, Desenvolvimento de habilidades de enfrentamento",
     suggestedDurations: [
       { value: 7, label: "7 dias - Entre sessões" },
       { value: 14, label: "14 dias - Quinzenal" },
       { value: 30, label: "30 dias - Mensal" },
     ],
     structuredDataTypes: STRUCTURED_DATA_BY_SPECIALTY.psychology,
     suggestedContactPoints: [
       { type: "structured_data", label: "Registro de humor", description: "Como está seu humor hoje?" },
       { type: "structured_data", label: "Qualidade do sono", description: "Como dormiu?" },
       { type: "open_question", label: "Diário emocional", description: "Reflexões do dia" },
       { type: "closed_question", label: "Praticou técnicas?", description: "Respiração, mindfulness, etc." },
       { type: "educational_message", label: "Psicoeducação", description: "Conteúdo informativo" },
     ],
     criticalKeywords: ["suicídio", "me machucar", "não aguento mais", "quero morrer", "autolesão", "crise", "pânico intenso"],
     defaultIcon: "brain",
   },
   "Psiquiatria": {
     id: "psiquiatria",
     label: "Psiquiatria",
     category: "psychology",
     clinicalConditionLabel: "Diagnóstico/Condição",
     clinicalConditionPlaceholder: "Ex: TAG, TDM, TDAH, Transtorno Bipolar",
     clinicalObjectiveLabel: "Objetivo do Tratamento",
     clinicalObjectivePlaceholder: "Ex: Remissão de sintomas, Estabilização do humor",
     suggestedDurations: [
       { value: 14, label: "14 dias - Ajuste medicamentoso" },
       { value: 30, label: "30 dias - Acompanhamento mensal" },
       { value: 60, label: "60 dias - Fase de manutenção" },
     ],
     structuredDataTypes: STRUCTURED_DATA_BY_SPECIALTY.psychology,
     suggestedContactPoints: [
       { type: "structured_data", label: "Escala de humor", description: "Registro diário" },
       { type: "closed_question", label: "Efeitos colaterais", description: "Sentiu algo diferente?" },
       { type: "reminder", label: "Medicação", description: "Lembrete do horário" },
       { type: "structured_data", label: "Horas de sono", description: "Quantidade dormida" },
     ],
     criticalKeywords: ["suicídio", "me machucar", "não aguento mais", "quero morrer", "alucinação", "mania", "euforia extrema", "insônia total"],
     defaultIcon: "brain",
   },
   // Physiotherapy
   "Fisioterapia": {
     id: "fisioterapia",
     label: "Fisioterapia",
     category: "physiotherapy",
     clinicalConditionLabel: "Condição/Lesão",
     clinicalConditionPlaceholder: "Ex: Lombalgia, Pós-operatório de LCA, Tendinite",
     clinicalObjectiveLabel: "Objetivo Funcional",
     clinicalObjectivePlaceholder: "Ex: Retorno às atividades em 6 semanas, Amplitude completa",
     suggestedDurations: [
       { value: 7, label: "7 dias - Fase aguda" },
       { value: 14, label: "14 dias - Fase subaguda" },
       { value: 30, label: "30 dias - Reabilitação" },
       { value: 60, label: "60 dias - Programa completo" },
     ],
     structuredDataTypes: STRUCTURED_DATA_BY_SPECIALTY.physiotherapy,
     suggestedContactPoints: [
       { type: "structured_data", label: "Escala de dor", description: "Nível de dor hoje" },
       { type: "closed_question", label: "Fez os exercícios?", description: "Adesão ao programa" },
       { type: "structured_data", label: "Repetições realizadas", description: "Quantas séries fez?" },
       { type: "educational_message", label: "Vídeo do exercício", description: "Demonstração" },
       { type: "open_question", label: "Dificuldades", description: "Algum exercício causou dor?" },
     ],
     criticalKeywords: ["dor intensa", "inchaço", "não consigo mover", "dormência", "piora significativa", "travou"],
     defaultIcon: "move",
   },
   "Ortopedia": {
     id: "ortopedia",
     label: "Ortopedia",
     category: "physiotherapy",
     clinicalConditionLabel: "Diagnóstico Ortopédico",
     clinicalConditionPlaceholder: "Ex: Fratura de clavícula, Artrose de joelho",
     clinicalObjectiveLabel: "Objetivo do Tratamento",
     clinicalObjectivePlaceholder: "Ex: Consolidação óssea, Redução da dor",
     suggestedDurations: [
       { value: 14, label: "14 dias - Pós-operatório imediato" },
       { value: 30, label: "30 dias - Reavaliação" },
       { value: 60, label: "60 dias - Reabilitação" },
     ],
     structuredDataTypes: STRUCTURED_DATA_BY_SPECIALTY.physiotherapy,
     suggestedContactPoints: [
       { type: "structured_data", label: "Nível de dor", description: "Escala de dor" },
       { type: "closed_question", label: "Inchaço?", description: "Presença de edema" },
       { type: "reminder", label: "Medicação analgésica", description: "Horário do analgésico" },
     ],
     criticalKeywords: ["dor insuportável", "febre", "secreção", "dormência", "formigamento intenso"],
     defaultIcon: "bone",
   },
   // Dentistry
   "Odontologia": {
     id: "odontologia",
     label: "Odontologia",
     category: "dentistry",
     clinicalConditionLabel: "Tratamento/Procedimento",
     clinicalConditionPlaceholder: "Ex: Tratamento Periodontal, Implante, Extração",
     clinicalObjectiveLabel: "Objetivo do Tratamento",
     clinicalObjectivePlaceholder: "Ex: Controle da periodontite, Osseointegração",
     suggestedDurations: [
       { value: 7, label: "7 dias - Pós-operatório" },
       { value: 14, label: "14 dias - Cicatrização" },
       { value: 30, label: "30 dias - Manutenção" },
       { value: 90, label: "90 dias - Programa periodontal" },
     ],
     structuredDataTypes: STRUCTURED_DATA_BY_SPECIALTY.dentistry,
     suggestedContactPoints: [
       { type: "structured_data", label: "Escovações/dia", description: "Frequência de escovação" },
       { type: "structured_data", label: "Uso de fio dental", description: "Vezes por dia" },
       { type: "structured_data", label: "Dor/Sensibilidade", description: "Nível de desconforto" },
       { type: "closed_question", label: "Sangramento?", description: "Gengiva sangrou?" },
       { type: "educational_message", label: "Técnica de escovação", description: "Orientações" },
       { type: "reminder", label: "Bochechos", description: "Lembrete de enxaguante" },
     ],
     criticalKeywords: ["dor forte", "inchaço", "sangramento intenso", "pus", "febre", "não consigo abrir a boca"],
     defaultIcon: "smile",
   },
   // Other specialties
   "Dermatologia": {
     id: "dermatologia",
     label: "Dermatologia",
     category: "medicine",
     clinicalConditionLabel: "Condição Dermatológica",
     clinicalConditionPlaceholder: "Ex: Acne, Dermatite, Psoríase",
     clinicalObjectiveLabel: "Objetivo do Tratamento",
     clinicalObjectivePlaceholder: "Ex: Controle das lesões, Melhora cosmética",
     suggestedDurations: [
       { value: 30, label: "30 dias - Avaliação inicial" },
       { value: 60, label: "60 dias - Ajuste terapêutico" },
       { value: 90, label: "90 dias - Tratamento completo" },
     ],
     structuredDataTypes: STRUCTURED_DATA_BY_SPECIALTY.medicine,
     suggestedContactPoints: [
       { type: "structured_data", label: "Foto da lesão", description: "Registro fotográfico" },
       { type: "closed_question", label: "Adesão ao tratamento", description: "Usou os produtos?" },
       { type: "reminder", label: "Aplicação do medicamento", description: "Horário da pomada/creme" },
     ],
     criticalKeywords: ["piora intensa", "febre", "inchaço facial", "reação alérgica"],
     defaultIcon: "scan",
   },
   "Pediatria": {
     id: "pediatria",
     label: "Pediatria",
     category: "medicine",
     clinicalConditionLabel: "Condição/Acompanhamento",
     clinicalConditionPlaceholder: "Ex: Puericultura, Infecção respiratória, Alergia alimentar",
     clinicalObjectiveLabel: "Objetivo do Acompanhamento",
     clinicalObjectivePlaceholder: "Ex: Monitorar crescimento, Resolução do quadro",
     suggestedDurations: [
       { value: 7, label: "7 dias - Quadro agudo" },
       { value: 30, label: "30 dias - Acompanhamento" },
     ],
     structuredDataTypes: STRUCTURED_DATA_BY_SPECIALTY.medicine,
     suggestedContactPoints: [
       { type: "structured_data", label: "Temperatura", description: "Febre?" },
       { type: "open_question", label: "Como está a criança?", description: "Estado geral" },
       { type: "reminder", label: "Medicação", description: "Horário do remédio" },
     ],
     criticalKeywords: ["febre alta", "convulsão", "não come", "muito sonolento", "manchas", "dificuldade respirar"],
     defaultIcon: "baby",
   },
   "Fonoaudiologia": {
     id: "fonoaudiologia",
     label: "Fonoaudiologia",
     category: "other",
     clinicalConditionLabel: "Foco Terapêutico",
     clinicalConditionPlaceholder: "Ex: Disfagia, Afasia, Transtorno de linguagem",
     clinicalObjectiveLabel: "Objetivo da Terapia",
     clinicalObjectivePlaceholder: "Ex: Melhora da deglutição, Desenvolvimento da fala",
     suggestedDurations: [
       { value: 7, label: "7 dias - Entre sessões" },
       { value: 30, label: "30 dias - Fase de tratamento" },
     ],
     structuredDataTypes: STRUCTURED_DATA_BY_SPECIALTY.other,
     suggestedContactPoints: [
       { type: "closed_question", label: "Fez os exercícios?", description: "Adesão" },
       { type: "educational_message", label: "Vídeo demonstrativo", description: "Exercício do dia" },
     ],
     criticalKeywords: ["engasgo", "dificuldade respirar", "não consegue engolir"],
     defaultIcon: "mic",
   },
   "Terapia Ocupacional": {
     id: "terapia-ocupacional",
     label: "Terapia Ocupacional",
     category: "other",
     clinicalConditionLabel: "Área de Intervenção",
     clinicalConditionPlaceholder: "Ex: AVDs, Reabilitação cognitiva, Integração sensorial",
     clinicalObjectiveLabel: "Objetivo Funcional",
     clinicalObjectivePlaceholder: "Ex: Independência nas AVDs, Melhora da coordenação",
     suggestedDurations: [
       { value: 7, label: "7 dias - Entre sessões" },
       { value: 30, label: "30 dias - Programa" },
     ],
     structuredDataTypes: STRUCTURED_DATA_BY_SPECIALTY.other,
     suggestedContactPoints: [
       { type: "closed_question", label: "Realizou as atividades?", description: "Adesão" },
       { type: "open_question", label: "Dificuldades encontradas", description: "O que foi difícil?" },
     ],
     criticalKeywords: ["queda", "não consegue realizar", "piora significativa"],
     defaultIcon: "hand",
   },
   "Geriatria": {
     id: "geriatria",
     label: "Geriatria",
     category: "medicine",
     clinicalConditionLabel: "Condições/Síndromes Geriátricas",
     clinicalConditionPlaceholder: "Ex: Fragilidade, Polifarmácia, Declínio cognitivo",
     clinicalObjectiveLabel: "Objetivo do Cuidado",
     clinicalObjectivePlaceholder: "Ex: Manutenção da funcionalidade, Prevenção de quedas",
     suggestedDurations: [
       { value: 30, label: "30 dias - Acompanhamento" },
       { value: 60, label: "60 dias - Monitoramento contínuo" },
     ],
     structuredDataTypes: STRUCTURED_DATA_BY_SPECIALTY.medicine,
     suggestedContactPoints: [
       { type: "closed_question", label: "Tomou medicações?", description: "Adesão" },
       { type: "structured_data", label: "Pressão arterial", description: "Registro de PA" },
       { type: "open_question", label: "Como está se sentindo?", description: "Estado geral" },
     ],
     criticalKeywords: ["queda", "confusão", "não reconhece", "não come", "febre", "dor forte"],
     defaultIcon: "users",
   },
   "Reumatologia": {
     id: "reumatologia",
     label: "Reumatologia",
     category: "medicine",
     clinicalConditionLabel: "Doença Reumatológica",
     clinicalConditionPlaceholder: "Ex: Artrite Reumatoide, Lúpus, Fibromialgia",
     clinicalObjectiveLabel: "Objetivo Terapêutico",
     clinicalObjectivePlaceholder: "Ex: Controle da atividade da doença, Redução da dor",
     suggestedDurations: [
       { value: 30, label: "30 dias - Monitoramento" },
       { value: 60, label: "60 dias - Ajuste terapêutico" },
     ],
     structuredDataTypes: STRUCTURED_DATA_BY_SPECIALTY.medicine,
     suggestedContactPoints: [
       { type: "structured_data", label: "Dor articular", description: "Escala de dor" },
       { type: "structured_data", label: "Rigidez matinal", description: "Duração em minutos" },
       { type: "closed_question", label: "Adesão à medicação", description: "Tomou conforme prescrito?" },
     ],
     criticalKeywords: ["febre", "inchaço intenso", "não consigo mover", "manchas na pele", "dor insuportável"],
     defaultIcon: "bone",
   },
   "Medicina Esportiva": {
     id: "medicina-esportiva",
     label: "Medicina Esportiva",
     category: "medicine",
     clinicalConditionLabel: "Lesão/Condição",
     clinicalConditionPlaceholder: "Ex: Lesão muscular, Overtraining, Retorno ao esporte",
     clinicalObjectiveLabel: "Objetivo",
     clinicalObjectivePlaceholder: "Ex: Retorno seguro ao esporte, Prevenção de recidiva",
     suggestedDurations: [
       { value: 14, label: "14 dias - Fase aguda" },
       { value: 30, label: "30 dias - Reabilitação" },
       { value: 60, label: "60 dias - Retorno ao esporte" },
     ],
     structuredDataTypes: STRUCTURED_DATA_BY_SPECIALTY.physiotherapy,
     suggestedContactPoints: [
       { type: "structured_data", label: "Dor ao treinar", description: "Escala de dor" },
       { type: "closed_question", label: "Treinou hoje?", description: "Registro de treino" },
       { type: "open_question", label: "Como foi o treino?", description: "Sensações durante" },
     ],
     criticalKeywords: ["dor aguda", "estalou", "inchaço", "não consigo apoiar", "dormência"],
     defaultIcon: "trophy",
   },
   "Outro": {
     id: "outro",
     label: "Outro",
     category: "other",
     clinicalConditionLabel: "Condição/Situação",
     clinicalConditionPlaceholder: "Descreva a condição ou situação clínica",
     clinicalObjectiveLabel: "Objetivo",
     clinicalObjectivePlaceholder: "Qual resultado espera alcançar?",
     suggestedDurations: [
       { value: 7, label: "7 dias" },
       { value: 14, label: "14 dias" },
       { value: 30, label: "30 dias" },
       { value: 60, label: "60 dias" },
       { value: 90, label: "90 dias" },
     ],
     structuredDataTypes: STRUCTURED_DATA_BY_SPECIALTY.other,
     suggestedContactPoints: [],
     criticalKeywords: ["urgente", "emergência", "piora grave"],
     defaultIcon: "route",
   },
 };
 
 export const getSpecialtyConfig = (specialty: string | null | undefined): SpecialtyConfig => {
   if (!specialty) return SPECIALTY_CONFIGS["Outro"];
   return SPECIALTY_CONFIGS[specialty] || SPECIALTY_CONFIGS["Outro"];
 };
 
 export const getSpecialtyCategory = (specialty: string | null | undefined): string => {
   return getSpecialtyConfig(specialty).category;
 };